---
- name: Enable crgroups
  ansible.builtin.import_tasks:
    file: cgroups.yml
  tags:
    - always
    - microk8s

- name: Install microk8s
  ansible.builtin.import_tasks:
    file: install.yml
  tags:
    - always
    - microk8s
    
- name: Reset Microk8s
  tasks:
    - name: Reset Microk8s
      command: microk8s reset
  tags:
    - always
    - microk8s

- name: Configure microk8s Users
  ansible.builtin.include_tasks:
    file: configure-groups.yml
  when:
    - microk8s_users is defined
    - microk8s_users not in ([], None, '', omit)
  tags:
    - microk8s
    - microk8s.users
    - notest

- name: Configure High Availability
  ansible.builtin.include_tasks:
    file: configure-HA.yml
  when:
    - microk8s_enable_ha | bool
  tags:
    - microk8s
    - microk8s.ha

- name: Configure plugins
  ansible.builtin.include_tasks:
    file: configure-plugins.yml
  run_once: true
  when:
    - microk8s_plugins is defined
  tags:
    - microk8s
    - microk8s.plugins
...
